version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5194:80"
    networks:
      - app-network
    volumes:
      - sqlite-data:/app/Data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Issuer=BloggingPlatform
      - Jwt__Audience=BloggingPlatform
      - Jwt__Key=YourSuperSecureSecretKey1234567890

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite-data:
