version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5194:80"
    networks:
      - app-network
    volumes:
      - sqlite-data:/app/Data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Issuer=BloggingPlatform
      - Jwt__Audience=BloggingPlatform
      - Jwt__Key=YourSuperSecureSecretKey1234567890

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge

volumes:
  sqlite-data:
